### Recuperando os dados

In [23]:
import numpy as np
import pandas as pd

In [24]:
FILE_PATH_2018 = './BasesRN/cadunico_rn_2018.csv'
cadUnicoRN2018 = pd.read_csv(FILE_PATH_2018, sep=';', low_memory=False)

In [25]:
FILE_PATH_2017 = './BasesRN/cadunico_rn_2017.csv'
cadUnicoRN2017 = pd.read_csv(FILE_PATH_2017, sep=';', low_memory=False)

In [26]:
FILE_PATH_2016 = './BasesRN/cadunico_rn_2016.csv'
cadUnicoRN2016 = pd.read_csv(FILE_PATH_2016, sep=';', low_memory=False)

In [27]:
# Juntando os dois datasets
cadUnicoRN = pd.concat([cadUnicoRN2018, cadUnicoRN2017, cadUnicoRN2016], ignore_index=True)

### Entendendo a estrutura os dados

In [28]:
cadUnicoRN

,cd_ibge,estrato,classf,id_familia,dat_cadastramento_fam,dat_alteracao_fam,vlr_renda_media_fam,dat_atualizacao_familia,cod_local_domic_fam,cod_especie_domic_fam,...,cod_familia_indigena_fam,ind_familia_quilombola_fam,nom_estab_assist_saude_fam,cod_eas_fam,nom_centro_assist_fam,cod_centro_assist_fam,ind_parc_mds_fam,marc_pbf,qtde_pessoas,peso.fam
0,2414803,1,2,3022.0,2017-12-04,2018-10-01,312.0,2017-12-04,1.0,1.0,...,2.0,2.0,NaN,NaN,NaN,NaN,205.0,0,3,550277487854843
1,2407104,2,2,3023.0,2017-03-28,2017-03-30,75.0,2017-03-28,1.0,1.0,...,2.0,2.0,E S F MORADA DA FE,2473488.0,CRAS FABRICIO GOMES PEDROZA,2.407102e+10,0.0,1,2,550309766683735
2,2402600,2,2,3024.0,2012-09-24,2016-04-15,60.0,2016-04-15,1.0,1.0,...,2.0,2.0,NaN,NaN,NaN,NaN,0.0,1,5,550245146328323
3,2402600,2,2,3025.0,2011-02-17,2015-03-17,394.0,2015-03-17,1.0,1.0,...,2.0,2.0,NaN,NaN,NaN,NaN,0.0,0,2,550245146328323
4,2403608,2,2,3026.0,2012-01-09,2018-10-01,66.0,2017-03-13,1.0,1.0,...,2.0,2.0,NaN,NaN,NaN,NaN,205.0,1,3,550377509002049
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
336634,2408102,2,1,4304045.0,2014-09-25,2014-09-25,50,2014-09-25,1.0,1.0,...,2.0,2.0,NaN,NaN,NaN,NaN,0.0,1,2,"5,33778130097748"
336635,2408102,2,1,4304046.0,2013-11-22,2016-06-08,330,2016-06-08,1.0,1.0,...,2.0,2.0,NaN,NaN,CRAS FELIPE CAMARAO,2.408104e+10,0.0,1,2,"5,33778130097748"
336636,2408102,2,1,4304047.0,2009-05-28,2016-12-08,70,2012-09-21,1.0,1.0,...,2.0,2.0,NaN,NaN,NaN,NaN,NaN,0,2,"5,33778130097748"
336637,2408102,2,1,4304048.0,2009-11-30,2013-10-17,50,2013-10-17,1.0,1.0,...,2.0,2.0,NaN,NaN,NaN,NaN,NaN,0,3,"5,33778130097748"
336638,2408102,2,1,4304049.0,2003-10-17,2015-09-15,162,2015-09-15,1.0,1.0,...,2.0,2.0,NaN,NaN,NaN,NaN,0.0,1,4,"5,33778130097748"

In [29]:
cadUnicoRN.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 336639 entries, 0 to 336638
Data columns (total 31 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   cd_ibge                        336639 non-null  int64
 1   estrato                        336639 non-null  int64
 2   classf                         336639 non-null  int64
 3   id_familia                     336639 non-null  float64
 4   dat_cadastramento_fam          336639 non-null  object
 5   dat_alteracao_fam              336639 non-null  object
 6   vlr_renda_media_fam            336637 non-null  object
 7   dat_atualizacao_familia        336639 non-null  object
 8   cod_local_domic_fam            336193 non-null  float64
 9   cod_especie_domic_fam          336193 non-null  float64
 10  qtd_comodos_domic_fam          325722 non-null  float64
 11  qtd_comodos_dormitorio_fam     325812 non-null  float64
 12  cod_material_piso_fam          325861 non-null  float64
 13  cod_material_domic_fam         325861 non-null  float64
 14  cod_agua_canalizada_fam        325861 non-null  float64
 15  cod_abaste_agua_domic_fam      325861 non-null  float64
 16  cod_banheiro_domic_fam         325861 non-null  float64
 17  cod_escoa_sanitario_domic_fam  316069 non-null  float64
 18  cod_destino_lixo_domic_fam     325861 non-null  float64
 19  cod_iluminacao_domic_fam       325861 non-null  float64
 20  cod_calcamento_domic_fam       325861 non-null  float64
 21  cod_familia_indigena_fam       336639 non-null  float64
 22  ind_familia_quilombola_fam     336219 non-null  float64
 23  nom_estab_assist_saude_fam     155478 non-null  object
 24  cod_eas_fam                    155478 non-null  float64
 25  nom_centro_assist_fam          72008 non-null   object
 26  cod_centro_assist_fam          72008 non-null   float64
 27  ind_parc_mds_fam               299519 non-null  float64
 28  marc_pbf                       336639 non-null  int64
 29  qtde_pessoas                   336639 non-null  int64
 30  peso.fam                       336639 non-null  object
dtypes: float64(19), int64(5), object(7)
memory usage: 79.6+ MB

In [30]:
cadUnicoRN.describe()

,cd_ibge,estrato,classf,id_familia,cod_local_domic_fam,cod_especie_domic_fam,qtd_comodos_domic_fam,qtd_comodos_dormitorio_fam,cod_material_piso_fam,cod_material_domic_fam,...,cod_destino_lixo_domic_fam,cod_iluminacao_domic_fam,cod_calcamento_domic_fam,cod_familia_indigena_fam,ind_familia_quilombola_fam,cod_eas_fam,cod_centro_assist_fam,ind_parc_mds_fam,marc_pbf,qtde_pessoas
count,3.366390e+05,336639.000000,336639.00000,3.366390e+05,336193.000000,336193.000000,325722.000000,325812.000000,325861.000000,325861.000000,...,325861.000000,325861.000000,325861.000000,336639.000000,336219.000000,1.554780e+05,7.200800e+04,299519.000000,336639.000000,336639.00000
mean,2.406955e+06,1.711608,2.52289,2.154375e+06,1.264848,1.033121,4.792028,1.790364,3.032612,1.186132,...,1.395218,1.192766,1.847769,1.998752,1.996705,3.225510e+06,2.405849e+10,47.564852,0.572818,2.85750
std,3.912521e+03,0.453015,0.72698,1.523811e+06,0.441253,0.191836,1.318660,0.683495,1.480884,0.642033,...,0.824574,0.794986,0.964519,0.035300,0.057312,1.503159e+06,4.756996e+08,89.914328,0.494670,1.40624
min,2.400109e+06,1.000000,1.00000,8.600000e+01,1.000000,1.000000,0.000000,0.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,2.376000e+04,1.240100e+10,0.000000,0.000000,1.00000
25%,2.403251e+06,1.000000,2.00000,4.955820e+05,1.000000,1.000000,4.000000,1.000000,2.000000,1.000000,...,1.000000,1.000000,1.000000,2.000000,2.000000,2.410222e+06,2.404400e+10,0.000000,0.000000,2.00000
50%,2.408003e+06,2.000000,3.00000,2.083642e+06,1.000000,1.000000,5.000000,2.000000,2.000000,1.000000,...,1.000000,1.000000,1.000000,2.000000,2.000000,2.501945e+06,2.408002e+10,0.000000,1.000000,3.00000
75%,2.409100e+06,2.000000,3.00000,3.641998e+06,2.000000,1.000000,5.000000,2.000000,5.000000,1.000000,...,1.000000,1.000000,3.000000,2.000000,2.000000,3.149102e+06,2.410700e+10,0.000000,1.000000,4.00000
max,2.415008e+06,2.000000,3.00000,5.135668e+06,2.000000,3.000000,20.000000,20.000000,7.000000,8.000000,...,6.000000,6.000000,3.000000,2.000000,2.000000,9.542973e+06,2.414900e+10,306.000000,1.000000,16.00000

### Pré-processamento dos dados

In [31]:
# removendo colunas que não se encontram em um formato adequado para o treinamento de ML
cadUnicoRN = cadUnicoRN.drop(columns=['dat_cadastramento_fam', 'dat_alteracao_fam', 'dat_atualizacao_familia', 'nom_estab_assist_saude_fam', 'cod_eas_fam', 'nom_centro_assist_fam', 'cod_centro_assist_fam'])

cadUnicoRN.head()

,cd_ibge,estrato,classf,id_familia,vlr_renda_media_fam,cod_local_domic_fam,cod_especie_domic_fam,qtd_comodos_domic_fam,qtd_comodos_dormitorio_fam,cod_material_piso_fam,...,cod_escoa_sanitario_domic_fam,cod_destino_lixo_domic_fam,cod_iluminacao_domic_fam,cod_calcamento_domic_fam,cod_familia_indigena_fam,ind_familia_quilombola_fam,ind_parc_mds_fam,marc_pbf,qtde_pessoas,peso.fam
0,2414803,1,2,3022.0,312.0,1.0,1.0,4.0,1.0,2.0,...,3.0,2.0,1.0,1.0,2.0,2.0,205.0,0,3,550277487854843
1,2407104,2,2,3023.0,75.0,1.0,1.0,4.0,1.0,5.0,...,2.0,1.0,1.0,1.0,2.0,2.0,0.0,1,2,550309766683735
2,2402600,2,2,3024.0,60.0,1.0,1.0,5.0,2.0,2.0,...,2.0,1.0,1.0,3.0,2.0,2.0,0.0,1,5,550245146328323
3,2402600,2,2,3025.0,394.0,1.0,1.0,5.0,2.0,5.0,...,3.0,1.0,1.0,1.0,2.0,2.0,0.0,0,2,550245146328323
4,2403608,2,2,3026.0,66.0,1.0,1.0,5.0,2.0,2.0,...,2.0,1.0,1.0,1.0,2.0,2.0,205.0,1,3,550377509002049

In [32]:
# verificando linhas duplicadas devido a mesclagem de diferentes datasets
duplicados = cadUnicoRN.duplicated(subset=['id_familia'], keep=False)

# print("Registros dublicados encontrados");
# print(cadUnicoRN[duplicados])

cadUnicoRN = cadUnicoRN.drop_duplicates(subset=['id_familia'], keep='last')

In [33]:
# colunas que precisam de tratamento de tipos
columns_to_convert = ['vlr_renda_media_fam', 'peso.fam']

for column in columns_to_convert:
    cadUnicoRN[column] = cadUnicoRN[column].replace(',', '.', regex=True).astype(float)

# verificando valores ausentes em cada coluna
missing_values = cadUnicoRN.isnull().sum()

print('As colunas com valores ausentes são:\n', (missing_values))

As colunas com valores ausentes são:
 cd_ibge                              0
estrato                              0
classf                               0
id_familia                           0
vlr_renda_media_fam                  2
cod_local_domic_fam                430
cod_especie_domic_fam              430
qtd_comodos_domic_fam             9412
qtd_comodos_dormitorio_fam        9331
cod_material_piso_fam             9286
cod_material_domic_fam            9286
cod_agua_canalizada_fam           9286
cod_abaste_agua_domic_fam         9286
cod_banheiro_domic_fam            9286
cod_escoa_sanitario_domic_fam    17954
cod_destino_lixo_domic_fam        9286
cod_iluminacao_domic_fam          9286
cod_calcamento_domic_fam          9286
cod_familia_indigena_fam             0
ind_familia_quilombola_fam         385
ind_parc_mds_fam                 36157
marc_pbf                             0
qtde_pessoas                         0
peso.fam                             0
dtype: int64

In [34]:
columns_to_remove = ['cod_escoa_sanitario_domic_fam', 'ind_parc_mds_fam', 'id_familia']

cadUnicoRN = cadUnicoRN.drop(columns=columns_to_remove, axis=1)

# removendo linhas com valores ausentes
cadUnicoRN = cadUnicoRN.dropna()

missing_values = cadUnicoRN.isnull().sum()
print('As colunas com valores ausentes são:\n', (missing_values))

As colunas com valores ausentes são:
 cd_ibge                       0
estrato                       0
classf                        0
vlr_renda_media_fam           0
cod_local_domic_fam           0
cod_especie_domic_fam         0
qtd_comodos_domic_fam         0
qtd_comodos_dormitorio_fam    0
cod_material_piso_fam         0
cod_material_domic_fam        0
cod_agua_canalizada_fam       0
cod_abaste_agua_domic_fam     0
cod_banheiro_domic_fam        0
cod_destino_lixo_domic_fam    0
cod_iluminacao_domic_fam      0
cod_calcamento_domic_fam      0
cod_familia_indigena_fam      0
ind_familia_quilombola_fam    0
marc_pbf                      0
qtde_pessoas                  0
peso.fam                      0
dtype: int64

In [35]:
feature_names = cadUnicoRN.columns.tolist()
feature_names.remove('marc_pbf')

In [36]:
# identificando colunas com apenas um valor
single_value_columns = [col for col in cadUnicoRN.columns if cadUnicoRN[col].nunique() == 1 | 0]

print(f"Colunas com um único valor: {single_value_columns}")

cadUnicoRN = cadUnicoRN.drop(columns=single_value_columns)

Colunas com um único valor: ['cod_especie_domic_fam', 'cod_familia_indigena_fam']

In [37]:
cadUnicoRN.info()

<class 'pandas.core.frame.DataFrame'>
Index: 296062 entries, 0 to 336638
Data columns (total 19 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   cd_ibge                     296062 non-null  int64
 1   estrato                     296062 non-null  int64
 2   classf                      296062 non-null  int64
 3   vlr_renda_media_fam         296062 non-null  float64
 4   cod_local_domic_fam         296062 non-null  float64
 5   qtd_comodos_domic_fam       296062 non-null  float64
 6   qtd_comodos_dormitorio_fam  296062 non-null  float64
 7   cod_material_piso_fam       296062 non-null  float64
 8   cod_material_domic_fam      296062 non-null  float64
 9   cod_agua_canalizada_fam     296062 non-null  float64
 10  cod_abaste_agua_domic_fam   296062 non-null  float64
 11  cod_banheiro_domic_fam      296062 non-null  float64
 12  cod_destino_lixo_domic_fam  296062 non-null  float64
 13  cod_iluminacao_domic_fam    296062 non-null  float64
 14  cod_calcamento_domic_fam    296062 non-null  float64
 15  ind_familia_quilombola_fam  296062 non-null  float64
 16  marc_pbf                    296062 non-null  int64
 17  qtde_pessoas                296062 non-null  int64
 18  peso.fam                    296062 non-null  float64
dtypes: float64(14), int64(5)
memory usage: 45.2 MB

In [38]:
# removendo colunas que ainda não se encontram em um formato adequado para o treinamento de ML
cadUnicoRN = cadUnicoRN.drop(columns=['cd_ibge', 'estrato', 'peso.fam'])

In [39]:
cadUnicoRN.info()

<class 'pandas.core.frame.DataFrame'>
Index: 296062 entries, 0 to 336638
Data columns (total 16 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   classf                      296062 non-null  int64
 1   vlr_renda_media_fam         296062 non-null  float64
 2   cod_local_domic_fam         296062 non-null  float64
 3   qtd_comodos_domic_fam       296062 non-null  float64
 4   qtd_comodos_dormitorio_fam  296062 non-null  float64
 5   cod_material_piso_fam       296062 non-null  float64
 6   cod_material_domic_fam      296062 non-null  float64
 7   cod_agua_canalizada_fam     296062 non-null  float64
 8   cod_abaste_agua_domic_fam   296062 non-null  float64
 9   cod_banheiro_domic_fam      296062 non-null  float64
 10  cod_destino_lixo_domic_fam  296062 non-null  float64
 11  cod_iluminacao_domic_fam    296062 non-null  float64
 12  cod_calcamento_domic_fam    296062 non-null  float64
 13  ind_familia_quilombola_fam  296062 non-null  float64
 14  marc_pbf                    296062 non-null  int64
 15  qtde_pessoas                296062 non-null  int64
dtypes: float64(13), int64(3)
memory usage: 38.4 MB

In [40]:
def classificar(x):
    if x == 1:
        return 1
    elif x == 2:
        return 2
    elif x == 3:
        return 3
    elif x == 4:
        return 4
    elif x == 5:
        return 5
    else:
        return 6

cadUnicoRN['qtde_pessoas'] = cadUnicoRN['qtde_pessoas'].apply(classificar)
cadUnicoRN['qtde_pessoas'].value_counts()

qtde_pessoas
2    82941
3    80895
4    51144
1    46833
5    21204
6    13045
Name: count, dtype: int64

In [41]:
print(cadUnicoRN.shape)
print(cadUnicoRN.head())

(296062, 16)
   classf  vlr_renda_media_fam  cod_local_domic_fam  qtd_comodos_domic_fam  \
0       2                312.0                  1.0                    4.0
1       2                 75.0                  1.0                    4.0
2       2                 60.0                  1.0                    5.0
3       2                394.0                  1.0                    5.0
4       2                 66.0                  1.0                    5.0

   qtd_comodos_dormitorio_fam  cod_material_piso_fam  cod_material_domic_fam  \
0                         1.0                    2.0                     1.0
1                         1.0                    5.0                     1.0
2                         2.0                    2.0                     1.0
3                         2.0                    5.0                     1.0
4                         2.0                    2.0                     1.0

   cod_agua_canalizada_fam  cod_abaste_agua_domic_fam  cod_banheiro_domic_fam  \
0                      1.0                        1.0                     1.0
1                      2.0                        4.0                     1.0
2                      1.0                        1.0                     1.0
3                      1.0                        1.0                     1.0
4                      1.0                        1.0                     1.0

   cod_destino_lixo_domic_fam  cod_iluminacao_domic_fam  \
0                         2.0                       1.0
1                         1.0                       1.0
2                         1.0                       1.0
3                         1.0                       1.0
4                         1.0                       1.0

   cod_calcamento_domic_fam  ind_familia_quilombola_fam  marc_pbf  \
0                       1.0                         2.0         0
1                       1.0                         2.0         1
2                       3.0                         2.0         1
3                       1.0                         2.0         0
4                       1.0                         2.0         1

   qtde_pessoas
0             3
1             2
2             5
3             2
4             3

In [42]:
cadUnicoRN.to_csv('./BasesRN/cadunico_rn_cleaned.csv', sep=';')